export enum TitleConstDesc {
	ID = 'Unique transaction ID',
	Signup_time = 'When the user signed up',
	Purchase_time = 'When the transaction/order was placed',
	Signup_purchase_diff_sec = 'Seconds between Signup Date and Purchase Date',
	Gender = 'User Gender',
	Age = 'User Age',
	User_fingerprint = 'Hexed with Gender, Age',
	User_fingerprint_velocity = 'User Fingerprint occurances in the last 24 hours',
	Purchase_value = 'How much the transaction was for',
	Source = 'Where the order originated from. Ads=Advertisement, Direct=?, SEO=?',
	Purchase_fingerprint = 'Hexed with Purchase Amount, Source',
	Purchase_fingerprint_velocity = 'Purchase Fingerprint occurances in the last 24 hours',
	IP_address = 'A way to identify device on the internet',
	IP_country = 'What country the IP address is coming from. May be empty',
	IP_history_fraudulent = 'IP address past history that were fraud',
	IP_history_total = 'IP address past history total',
	IP_address_velocity = 'IP address occurances in the last 24 hours',
	Device_id = 'A way to identify the phone or other device.',
	Browser = 'The name of the browser used',
	Device_fingerprint_velocity = 'Device Fingerprint occurances in the last 24 hours',
	Device_fingerprint = 'Hexed with Device ID, Browser',
	Is_fraud = '0 = Non Fraud, 1 = Fraud',
	Accept = 'Accept order as non fraudulent',
	Reject = 'Reject order as fraudulent',
}
