# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: dev on success

on:
  # Runs on pushes targeting the default branch
  workflow_run:
    workflows: ['NextJs test build']
    types: [completed]
    # branches: ['dev']
    branches: ['dev-workflow-on-success']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Merge_Into_Branch: main
  Merge_Into_Branch: dev-to-main-test-merge
  Merge_From_Branch: dev

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: create pull request
        # run: gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        run: |
          gh pr create \
            -B $Merge_Into_Branch \
            -H $Merge_From_Branch \
            --title 'Merge $Merge_From_Branch into $Merge_Into_Branch' \
            --body 'Merge to $Merge_Into_Branch after $Merge_From_Branch successfully passes it's tests.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
