# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: NextJs test build

on:
  # Runs on pushes targeting the default branch
  push:
    # branches: ['dev']
    branches: ['dev-workflow-on-success']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Merge_Into_Branch: main
  Merge_Into_Branch: dev-to-main-test-merge
  Merge_From_Branch: dev-workflow-on-success

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - name: Clean Install dependencies
        run: npm ci

      # - name: Build with Next.js
      #   run: npm run build

  cypress-e2e-run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: tempecho
        run: echo "cypress-e2e-run"
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Cypress tests
      #   uses: cypress-io/github-action@v6

  cypress-component-run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: tempecho
        run: echo "cypress-component-run"
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Cypress tests
      #   uses: cypress-io/github-action@v6
      #   with:
      #     component: true

  jest-run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: tempecho
        run: echo "jest-run"
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Install jest
      #   run: npm install --save-dev jest

      # - name: Jest Unit Tests
      #   run: npm run test:ci

  on-tests-success:
    runs-on: ubuntu-latest
    needs: ['cypress-e2e-run', 'cypress-component-run', 'jest-run']
    env:
      PR_CREATE_SCRIPT: |
        gh pr create \
          -B $Merge_Into_Branch \
          -H $Merge_From_Branch \
          --title 'Merge $Merge_From_Branch into $Merge_Into_Branch' \
          --body 'Merge to $Merge_Into_Branch after $Merge_From_Branch successfully passes its tests.'
    steps:
      - name: display create pull request script
        run: |
          echo "$PR_CREATE_SCRIPT"
          echo "gh pr create \
          -B $Merge_Into_Branch \
          -H $Merge_From_Branch \
          --title 'Merge $Merge_From_Branch into $Merge_Into_Branch' \
          --body 'Merge to $Merge_Into_Branch after $Merge_From_Branch successfully passes its tests.'"

      # - name: create pull request
      #   # run: gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      #   run: $PR_CREATE_SCRIPT
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
